# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id="template"
mod.name="Template"
mod.group="com.gmalvestiti.minecraft"
mod.version="1.0.0"

loomx.loom_version="1.17-SNAPSHOT"

deps.fabric_loader="0.19.3"
deps.caffeine="3.2.3"
deps.junit="6.1.2"
deps.mockito="5.23.0"

mod.description="Template description"
mod.author="GMalvestiti"
mod.contact_homepage="https://modrinth.com/user/Riser876"
mod.contact_sources="https://github.com/GMalvestiti/template"
mod.contact_issues="https://github.com/GMalvestiti/template/issues"
mod.license="MIT"

dev.debug=false
dev.javadoc=true
dev.snapshot=false
dev.username="Riser876"
dev.uuid="13957e2e-2731-4479-8a6d-d42f89f8d756"
dev.datagen=false

publish.type="stable"
publish.modrinth_id="template"
publish.modrinth_changelog="1.21"
publish.curseforge_id="1234567"
publish.curseforge_slug="template"
publish.curseforge_client=true
publish.curseforge_server=true
publish.auto_release=false
publish.dry_run=true


["1.21"]

deps.liteconfig="1.0.0-1.21"
publish.start="1.21"
publish.end="1.21.10"

[fabric."1.21"]
# Mod compatibility range in fabric.mod.json/neoforge.mods.toml
mod.mc_compat=">=1.21 <=1.21.10"
deps.fabric_api="0.102.0+1.21"

[neoforge."1.21"]
mod.mc_compat="[1.21, 1.21.10]"
deps.neoforge_loader="21.0.167"


["1.21.11"]

deps.liteconfig="1.0.0-1.21.11"
publish.start="1.21.11"
publish.end="1.21.11"

[fabric."1.21.11"]
mod.mc_compat=">=1.21.11 <=1.21.11"
deps.fabric_api="0.141.6+1.21.11"

[neoforge."1.21.11"]
mod.mc_compat="[1.21.11, 1.21.11]"
deps.neoforge_loader="21.11.45"


["26.1"]

deps.liteconfig="1.0.0-26.1"
publish.start="26.1"
publish.end="latest"

[fabric."26.1"]
mod.mc_compat=">=26.1"
deps.fabric_api="0.145.1+26.1"

[neoforge."26.1"]
mod.mc_compat="[26.1,)"
deps.neoforge_loader="26.1.0.19-beta"
