license="${license}"

modLoader="javafml"
loaderVersion="[1,)"

[[mods]]
modId="${id}"
displayName="${name}"
version="${version}"
authors="${author}"
description="${description}"

logoFile="assets/${id}/icon.png"
displayURL="${contact_homepage}"
issueTrackerUrl="${contact_issues}"

[[mixins]]
config="${id}.mixins.json"

[[dependencies.${id}]]
modId="minecraft"
type="required"
versionRange="${minecraft}"
ordering="NONE"
side="BOTH"

[[dependencies.${id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_loader},)"
ordering="NONE"
side="BOTH"
